### ISSUE TITLE
!= sucks even more than division used to

### ISSUE THREAD

**Issue by coolbeans1212** [Cyteon/modu#11]
ok so when i do this
`fn epicFunction(name) {`
`    if name == "Fred" {`
`        print("Your name is Fred! How cool");`
`    }`
`    if name != "Fred" { //why does modu not have else 😭`
`        print("Your name is not Fred. How sad.")`
`    }`
`}`
`epicFunction("goob");`

and run modu main.modu this is the output:
`PS C:\Users\Matei\desktop\Modu Testing> modu run main.modu`
`PS C:\Users\Matei\desktop\Modu Testing>`
thats right! it does ✨nothing✨!
![developer we have a bug](https://github.com/user-attachments/assets/afcc2c17-8686-4f51-aa64-5e170fc79919)

**Comment by Cyteon** [comment]
its not a != issue its a nesting issue

**Comment by coolbeans1212** [comment]
> its not a != issue its a nesting issue
:P

**Comment by Cyteon** [comment]
Fixed on packages branch
