### ISSUE TITLE
Division sucks

### ISSUE THREAD

**Issue by coolbeans1212** [Cyteon/modu#7]
so uh when i do the following code in modu (most epicest language):
`import "math" as math;`
`math.div(1,2);`
i get:
`⚠️ div takes 2 arguments
Traceback (most recent call last):
    File "<stdin>", line 3
Belive this is a bug? Report it: https://mateishome.page`
while i expect to get:
`No output`

please help me this is detrimental to my mental wellbeing
![Untitled2](https://github.com/user-attachments/assets/57d71559-0c8e-4349-bb6d-ecdb13bbcfed)

**Comment by Cyteon** [comment]
working on it rn

**Comment by Cyteon** [comment]
Fixed in https://github.com/Cyteon/modu/pull/8
